service: hello-world-han

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - "**/*"
  include:
    - ../smoking_detector/**/*
    - app.py

provider:
  name: aws
  region: us-west-2
  runtime: python3.6
  memorysize: 3096
  timeout: 30
  versionFunctions: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
      - "**/doc"
      - "**/tensorboard"
      - "**/tensorflow/contrib"
      - "**/tests"
      - "**/*.h5"
    noDeploy:
      - docutils
      - pip
      - tensorboard
      - setuptools
      - six
      - python-dateutil
    strip: false
    zip: true
